package com.convey.hardware.arduino;

import gnu.io.CommPortIdentifier;
import gnu.io.PortInUseException;
import gnu.io.SerialPort;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import gnu.io.UnsupportedCommOperationException;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.TooManyListenersException;
import javax.swing.JOptionPane;

/**
 * @projectName TEDxGame
 * @package com.convey.hardware.arduino
 * @filename ArduinoDevice.java
 * @encoding UTF-8
 * @author Ernesto Moyano
 * @date 28/08/2014 22:21:57
 */
public class ArduinoDevice implements SerialPortEventListener {

    private transient SerialPort serialPort;
    private transient BufferedReader input;
    private transient OutputStream output;
    private int dataRate;
    private String port;
    private boolean connected = false;
    private transient int packetsPerSecond = 0;
    private List<ArduinoEventListener> listeners;

    private List<Integer> dataRates = Arrays.asList(300, 1200, 2400, 4800,
            9600, 14400, 19200, 28800, 38400, 57600, 115200);

    /**
     *
     * Get data rates for Arduino devices
     *
     * @return
     */
    public List<Integer> getDataRates() {
        return dataRates;
    }

    /**
     *
     * Set the data rates for Arduino devices
     *
     * @param p_dataRates
     */
    public void setDataRates(final List<Integer> p_dataRates) {
        this.dataRates = p_dataRates;
    }

    /**
     * Return the state of the conection between the Arduino device
     *
     * @return
     */
    public boolean isConnected() {
        return connected;
    }

    /**
     *
     * Sets the state of Arduino Device
     *
     * @param connected
     */
    public void setConnected(final boolean connected) {
        this.connected = connected;
    }

    /**
     * Get port setted to connect to Arduino device
     *
     * @return
     */
    public String getPort() {
        return port;
    }

    /**
     * Set the port to connect to Arduino device
     *
     * @param port
     */
    public void setPort(final String port) {
        this.port = port;
    }

    /**
     * Get the data rate to be setted to Arduino device
     *
     * @return
     */
    public int getDataRate() {
        return dataRate;
    }

    /**
     * Set the data rate to the Arduino device
     *
     * @param dataRate
     */
    public void setDataRate(final int dataRate) {
        this.dataRate = dataRate;
    }

    /**
     * Sets the Arduino Event Listener that triggerall events generated by
     * Arduino
     *
     * @param p_listsner
     */
    public void addArduinoEventListener(final ArduinoEventListener p_listsner) {

        if (listeners == null) {
            listeners = new LinkedList<ArduinoEventListener>();
        }
        listeners.add(p_listsner);

    }

    /**
     * This method get a list of all ports avalaibles on the PC
     *
     * @return LinkedList containing all the ports
     */
    public LinkedList getAvailablesPorts() {
        final LinkedList ports = new LinkedList();
        try {
            final Enumeration puertoEnum = CommPortIdentifier.getPortIdentifiers();

            while (puertoEnum.hasMoreElements()) {

                final CommPortIdentifier actualPuertoID = (CommPortIdentifier) puertoEnum.nextElement();
                ports.add(actualPuertoID.getName());
            }
        } catch (UnsatisfiedLinkError ex) {
            System.err.println(ArduinoDevice.class.getName() + " Error 4x001 :" + ex.getMessage());
        } catch (NoClassDefFoundError ex) {
            System.err.println(ArduinoDevice.class.getName() + " Error 4x002 :" + ex.getMessage());
        }

        return ports;
    }

    /**
     * Initialize the serial port comunication
     */
    public void initialize() {

        initPacketsPerSecondCounter();
        CommPortIdentifier puertoID = null;
        final Enumeration puertoEnum = CommPortIdentifier.getPortIdentifiers();

        while (puertoEnum.hasMoreElements()) {
            CommPortIdentifier actualPuertoID = (CommPortIdentifier) puertoEnum.nextElement();

            if (port.equals(actualPuertoID.getName())) {
                puertoID = actualPuertoID;
                break;
            }
        }

        if (puertoID == null) {
            JOptionPane.showMessageDialog(null, "No ports avalaible");
            System.err.println(ArduinoDevice.class.getName() + " Error 4x003 :No ports avalaible");
            setConnected(false);
        } else {
            try {
                serialPort = (SerialPort) puertoID.open(this.getClass().getName(),
                        2000);

                serialPort.setSerialPortParams(dataRate,
                        SerialPort.DATABITS_8,
                        SerialPort.STOPBITS_1,
                        SerialPort.PARITY_NONE);

                input = new BufferedReader(new InputStreamReader(serialPort.getInputStream()));
                output = serialPort.getOutputStream();

                serialPort.addEventListener(this);
                serialPort.notifyOnDataAvailable(true);

                if (listeners != null) {
                    for (ArduinoEventListener listener : listeners) {
                        listener.onArduinoStateChanged("CONNECTED");
                        listener.onArduinoConnected();
                    }
                }

                setConnected(true);

            } catch (TooManyListenersException e) {
                setConnected(false);
                System.err.println(ArduinoDevice.class.getName() + " Error 4x004 :" + e.getMessage());
            } catch (PortInUseException e) {
                setConnected(false);
                System.err.println(ArduinoDevice.class.getName() + " Error 4x005 :" + e.getMessage());
            } catch (UnsupportedCommOperationException e) {
                setConnected(false);
                System.err.println(ArduinoDevice.class.getName() + " Error 4x006 :" + e.getMessage());
            } catch (IOException e) {
                setConnected(false);
                System.err.println(ArduinoDevice.class.getName() + " Error 4x007 :" + e.getMessage());
            }
        }
    }

    /**
     * This method should be called to allow serial flush for systems like linux
     */
    public synchronized void close() {
        if (serialPort != null) {
            serialPort.removeEventListener();
            serialPort.close();
            if (listeners != null) {
                for (ArduinoEventListener listener : listeners) {
                    listener.onArduinoStateChanged("DISCONNECTED");
                }
            }
        }
    }

    /**
     * This method is triggered when data is present in the serial port
     *
     * @param serialPortEvent
     */
    @Override
    public synchronized void serialEvent(SerialPortEvent serialPortEvent) {
        if (serialPortEvent.getEventType() == SerialPortEvent.DATA_AVAILABLE) {
            try {
                System.out.println("Received: " + input.readLine());
            } catch (IOException e) {
                System.err.println(ArduinoDevice.class.getName() + " Error 4x008 :" + e.getMessage());
            }
        }
    }

    private void initPacketsPerSecondCounter() {

        final Timer timerMetters = new Timer("Arduino pps Counter");
        timerMetters.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                if (listeners != null) {
                    for (ArduinoEventListener listener : listeners) {
                        listener.onCalculatePacketsPerSecond(packetsPerSecond);
                    }
                }
                packetsPerSecond = 0;
            }
        }, 0, 1000);

    }

    /**
     * Send the data over the network
     *
     * @param data
     */
    public void sendData(final String data) {
        try {
            output.write(data.getBytes());
            output.write('\n');
            packetsPerSecond++;
        } catch (IOException ex) {
            System.err.println(ArduinoDevice.class.getName()
                    + " Error 4x009 :" + ex.getMessage());
        }
    }
}
